name: ai_forgiveness_recommender
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment: 
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
   # http: ^1.2.2
  http: ^0.13.3
  provider: ^6.1.2
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/bird.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/bird1.png"
